/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.inventoryproductproject;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.reflect.TypeToken;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ray_g
 */
public class Main extends javax.swing.JFrame {
    
     List<Item> item = new ArrayList<>();
    TableRowSorter<TableFunctionalities> tableRowSorter = new TableRowSorter<>(); 

    /**
     * Creates new form InventoryProductsMain
     */
    public Main() {
        initComponents();
        readFile();
        initObjects();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panela = new javax.swing.JPanel();
        lblItem = new javax.swing.JLabel();
        fldItem = new javax.swing.JTextField();
        fldPrice = new javax.swing.JTextField();
        lblPrice = new javax.swing.JLabel();
        fldLot = new javax.swing.JTextField();
        lblLot = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        fldSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        scpItem = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        panela.setBackground(new java.awt.Color(230, 235, 224));
        panela.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panela.setForeground(new java.awt.Color(51, 255, 102));
        panela.setPreferredSize(new java.awt.Dimension(0, 0));
        panela.setLayout(null);

        lblItem.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblItem.setForeground(new java.awt.Color(0, 0, 0));
        lblItem.setText("Item Name");
        panela.add(lblItem);
        lblItem.setBounds(47, 50, 73, 17);
        panela.add(fldItem);
        fldItem.setBounds(23, 73, 140, 22);
        panela.add(fldPrice);
        fldPrice.setBounds(181, 73, 83, 22);

        lblPrice.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 0, 0));
        lblPrice.setText("Price");
        panela.add(lblPrice);
        lblPrice.setBounds(200, 50, 36, 17);

        fldLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fldLotActionPerformed(evt);
            }
        });
        panela.add(fldLot);
        fldLot.setBounds(282, 73, 91, 22);

        lblLot.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblLot.setForeground(new java.awt.Color(0, 0, 0));
        lblLot.setText("Lot");
        panela.add(lblLot);
        lblLot.setBounds(319, 50, 22, 17);

        btnAdd.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panela.add(btnAdd);
        btnAdd.setBounds(110, 120, 72, 24);

        btnRemove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(0, 0, 0));
        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        panela.add(btnRemove);
        btnRemove.setBounds(210, 120, 82, 24);

        lblSearch.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblSearch.setText("Search");
        panela.add(lblSearch);
        lblSearch.setBounds(23, 453, 49, 17);
        panela.add(fldSearch);
        fldSearch.setBounds(90, 450, 166, 22);

        btnSearch.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        panela.add(btnSearch);
        btnSearch.setBounds(268, 450, 75, 24);

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scpItem.setViewportView(tblItem);

        panela.add(scpItem);
        scpItem.setBounds(400, 40, 325, 445);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panela, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panela, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fldLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fldLotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fldLotActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Item pr = new Item();  // Crear una nueva instancia de Product
        TableFunctionalities itemModel = (TableFunctionalities) this.tblItem.getModel(); // Obtener el modelo de la tabla
        pr.setName(fldItem.getText());  // Establecer el nombre del producto con el texto del campo txtProduct

        try {
            pr.setPrice(Double.parseDouble(fldPrice.getText()));      // Establecer el precio del producto, convirtiendo el texto a double
            pr.setLot(Integer.parseInt(fldLot.getText()));       // Establecer el stock del producto, convirtiendo el texto a entero
        } catch (NumberFormatException e) {
            System.out.println("Error: Invalid Price or Stock format");  // Manejar cualquier error de formato al convertir el precio o el stock
            return;  // Salir del método si hay un error
        }

        try {
            double price = Double.parseDouble(fldPrice.getText());  // Convertir el texto del campo txtPrice a double
            int stock = Integer.parseInt(fldLot.getText());   // Convertir el texto del campo txtStock a entero
            if (price <= 0 || stock <= 0) {  // Verificar si el precio o el stock son valores no positivos
                throw new IllegalArgumentException("Error: Price or Stock must be a positive value."); // Lanzar una excepción si el precio o el stock no son valores positivos
            }
            pr.setPrice(price);   // Establecer el precio del producto
            pr.setLot(stock);   // Establecer el stock del producto
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());  // Capturar y mostrar un mensaje de error si se lanza una excepción
            return;  // Salir del método si hay un error
        }

        itemModel.addItem(pr);  // Agregar el producto al modelo de la tabla
        clearFields();  // Limpiar los campos del formulario

        saveProductsInv();  // Llamar a un método para guardar los productos en el inventario
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed

        RowFilter<TableFunctionalities, Integer> rowFilter = RowFilter.regexFilter(fldSearch.getText(), 0);  // Crear un filtro basado en el texto ingresado en txtSearch para la columna 0
        tableRowSorter.setRowFilter(rowFilter);  // Aplicar el filtro a la clasificación de filas de la tabla

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblItem.getSelectedRow();

        // Verificar si hay una fila seleccionada
        if (selectedRow != -1) {
            // Obtener el modelo de la tabla
            TableFunctionalities productInvTable = (TableFunctionalities) tblItem.getModel();

            // Obtener el índice de la fila seleccionada en el modelo
            int modelRowIndex = tblItem.convertRowIndexToModel(selectedRow);

            // Eliminar la fila del modelo
            productInvTable.removeItem(modelRowIndex);

            // Guardar los productos actualizados
            saveProductsInv();
        } else {
            // Si no se ha seleccionado ninguna fila, mostrar un mensaje de advertencia
            JOptionPane.showMessageDialog(this, "Please select a row to remove.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    // Método para limpiar los campos del formulario
    private void clearFields() {
        fldItem.setText("");  // Limpiar el campo de texto para el nombre del producto
        fldPrice.setText("");    // Limpiar el campo de texto para el precio del producto
        fldLot.setText("");    // Limpiar el campo de texto para el stock del producto
    }

// Método para inicializar los objetos relacionados con la tabla
    private void initObjects() {
        TableFunctionalities model = new TableFunctionalities(this.item);  // Crear un nuevo modelo de tabla con la lista de productos
        tableRowSorter = new TableRowSorter<>(model);  // Crear un clasificador de filas a partir del modelo
        tblItem.setRowSorter(tableRowSorter);  // Establecer el clasificador de filas en la tabla
        tblItem.setModel(model);  // Establecer el modelo de la tabla
    }

// Método para guardar la lista de productos en un archivo JSON
    private void saveProductsInv() {
        Gson gson = new GsonBuilder().create();  // Crear un objeto Gson para convertir la lista de productos a JSON
        String json = gson.toJson(this.item);  // Convertir la lista de productos a JSON

        try (FileWriter fileWriter = new FileWriter("ItemsInventory.json")) {  // Usar FileWriter para escribir en el archivo "ProductsInventory.json"
            fileWriter.write(json);  // Escribir el JSON en el archivo
            fileWriter.close();  // Cerrar el FileWriter
            System.out.println("Successfully saved: Item list");  // Mostrar un mensaje de éxito
        } catch (IOException e) {  // Manejar cualquier error de escritura
            System.err.println("Error saving item list to JSON: " + e.getMessage());  // Mostrar un mensaje de error
        }
    }

// Método para leer la lista de productos desde un archivo JSON
    private void readFile() {
        try {
            Gson gson = new GsonBuilder().create();  // Crear un objeto Gson para convertir el JSON a la lista de productos
            FileReader fileReader = new FileReader("ProductsInventory.json");  // Usar FileReader para leer el archivo "ProductsInventory.json"

            java.lang.reflect.Type typeListItems = new TypeToken<List<Item>>() {
            }.getType();  // Definir el tipo de datos para la lista de productos

            this.item = gson.fromJson(fileReader, typeListItems);  // Convertir el JSON a la lista de productos
        } catch (IOException e) {  // Manejar cualquier error de lectura
            System.err.println("Error reading JSON file: " + e.getMessage());  // Mostrar un mensaje de error
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JTextField fldItem;
    private javax.swing.JTextField fldLot;
    private javax.swing.JTextField fldPrice;
    private javax.swing.JTextField fldSearch;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblLot;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel panela;
    private javax.swing.JScrollPane scpItem;
    private javax.swing.JTable tblItem;
    // End of variables declaration//GEN-END:variables
}
